version: "3.9"
services:
  node-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: ./.env
    environment:
      - DB_USER=$DB_USER
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - PASSPHRASE=$PASSPHRASE
  db:
    image: "postgres:14.1-alpine"
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
