version: "3.9"
services:
  node-backend:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=jdbc:postgresql://db:5432/postgres
      - DB_NAME=files_data
      - DB_PASSWORD=dbpassword
      - DB_PORT=5432
  db:
    image: 'postgres:14.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - '5432:5432'
