apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: react-app
