apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html
spec:
  selector:
    matchLabels:
      app: app-html
  replicas: 1
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
        - name: app
          image: docker1509/frontendapp-html:main
          ports:
            - containerPort: 80
